### ISSUE TITLE
Error using "tag" option

### ISSUE THREAD

**Issue by juangnzalez** [djadmin/medium-cli#18]
Error using "tag" option
~ ❯❯❯ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12.3
BuildVersion:   16D32

NPM version:
 ~ ❯❯❯ npm -v                                                                                             ⏎
4.4.0

~ ❯❯❯ medium tag javascript
/usr/local/lib/node_modules/mediumcli/lib/post.js:71
        for (var i = 0, len = Math.min(count, items.length); i < len; i++) {
                                                   ^

TypeError: Cannot read property 'length' of undefined
    at processContent (/usr/local/lib/node_modules/mediumcli/lib/post.js:71:45)
    at /usr/local/lib/node_modules/mediumcli/lib/post.js:128:15
    at Request._callback (/usr/local/lib/node_modules/mediumcli/lib/post.js:29:4)
    at Request.self.callback (/usr/local/lib/node_modules/mediumcli/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/mediumcli/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/mediumcli/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by djadmin** [comment]
Fixed in the latest release!
