### ISSUE TITLE
Search related error using the tag option

### ISSUE THREAD

**Issue by evanniedojadlo** [djadmin/medium-cli#19]
I used the command `medium tag automation` and returned the following error within the output:

`/usr/local/lib/node_modules/mediumcli/lib/post.js:71
	for (var i = 0, len = Math.min(count, items.length); i < len; i++) {
	                                           ^

TypeError: Cannot read property 'length' of undefined
    at processContent (/usr/local/lib/node_modules/mediumcli/lib/post.js:71:45)
    at /usr/local/lib/node_modules/mediumcli/lib/post.js:128:15
    at Request._callback (/usr/local/lib/node_modules/mediumcli/lib/post.js:29:4)
    at Request.self.callback (/usr/local/lib/node_modules/mediumcli/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/mediumcli/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/mediumcli/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by ummahusla** [comment]
Worth to close this issue, as this was already mentioned in #18.
